-- Spicy Questions for Couples - "There are 2 types of people..."
-- 1000+ fun, flirty, zesty questions for couples

USE `two-people`;

-- Add category column if not exists
ALTER TABLE questions ADD COLUMN IF NOT EXISTS category VARCHAR(50) DEFAULT 'general';

-- Clear existing questions
DELETE FROM questions;

-- Reset auto increment
ALTER TABLE questions AUTO_INCREMENT = 1;

-- FLIRTY BASICS (1-100)
INSERT INTO questions (question_text, option_a_text, option_a_emoji, option_b_text, option_b_emoji, trait_name, category) VALUES
('In the morning you are...', 'Cuddle Monster', '🧸', 'Ready to GO', '😈', 'morning_vibe', 'flirty'),
('Your flirting style...', 'Subtle Hints', '😏', 'ZERO Chill', '🔥', 'flirt_style', 'flirty'),
('First move?', 'Wait for them', '🙈', 'I GO FIRST', '💪', 'initiative', 'flirty'),
('Lights...', 'ON 👀', '💡', 'OFF 🌙', '🕯️', 'ambiance', 'spicy'),
('Big spoon or...', 'Big Spoon', '🥄', 'Little Spoon', '🥣', 'cuddle_position', 'romantic'),
('PDA level...', 'Get a Room!', '🚪', 'Kiss Me Everywhere', '💋', 'pda_comfort', 'flirty'),
('Morning texts...', 'Good Morning ☀️', '🌅', 'You up? 😏', '🌙', 'text_style', 'flirty'),
('Date night...', 'Wine & Dine', '🍷', 'Netflix & ...', '📺', 'date_preference', 'romantic'),
('Love language...', 'Words', '💬', 'Actions 😈', '🔥', 'love_language', 'intimate'),
('Eye contact...', 'Shy Away', '🙈', 'LOCKED IN', '👁️', 'intensity', 'flirty'),
('Compliments...', 'Give Them', '🎁', 'Receive Them', '😊', 'compliment_style', 'romantic'),
('Jealous type?', 'Not At All', '😇', 'A Little... 👀', '😤', 'jealousy', 'honest'),
('Kiss style...', 'Soft & Sweet', '🦋', 'Deep & Passionate', '🔥', 'kiss_style', 'intimate'),
('Hand holding...', 'Fingers Locked', '🤝', 'Casual Touch', '✋', 'touch_style', 'romantic'),
('Dancing together...', 'Slow & Close', '💃', 'Dirty Dancing', '🕺', 'dance_style', 'spicy'),
('Surprise dates...', 'LOVE Them', '🎉', 'Need to Prepare', '📋', 'spontaneity', 'romantic'),
('Pet names...', 'Babe/Baby', '👶', 'Something Spicy', '🌶️', 'nicknames', 'flirty'),
('Matching outfits...', 'Absolutely', '👯', 'Never Ever', '🙅', 'couple_goals', 'silly'),
('Who says I love you first?', 'ME', '💕', 'THEM', '💗', 'vulnerability', 'romantic'),
('Breakfast in bed...', 'Make It', '👨‍🍳', 'Receive It', '😴', 'service', 'romantic'),
('Arguments end with...', 'Talking', '🗣️', 'Making Up 😏', '💋', 'conflict_style', 'honest'),
('Weekday romance...', 'Too Tired', '😴', 'ALWAYS Ready', '⚡', 'energy', 'spicy'),
('Weekend mornings...', 'Sleep In Together', '🛏️', 'Wake Up & Play', '🎮', 'weekend_vibe', 'romantic'),
('Shower...', 'Solo Time', '🚿', 'Room for Two', '🛁', 'intimacy', 'spicy'),
('Back rubs...', 'Give Them', '💆', 'Get Them', '😌', 'massage', 'romantic'),
('Whispering...', 'Sweet Nothings', '🥰', 'Spicy Somethings', '🔥', 'whisper_style', 'intimate'),
('Getting ready together...', 'Fun!', '💄', 'Need My Space', '🚪', 'routine', 'romantic'),
('Workout partner...', 'Yes Please', '💪', 'Solo Grind', '🏃', 'fitness', 'lifestyle'),
('Cooking together...', 'Teamwork!', '👨‍🍳', 'Stay Out of My Kitchen', '🔪', 'cooking', 'lifestyle'),
('Road trip vibes...', 'Sing Along!', '🎤', 'Hands Busy 😏', '👀', 'travel', 'spicy');

-- SPICY & INTIMATE (31-100)
INSERT INTO questions (question_text, option_a_text, option_a_emoji, option_b_text, option_b_emoji, trait_name, category) VALUES
('Roleplay...', 'Yes Please!', '🎭', 'Just Be Us', '💑', 'roleplay', 'spicy'),
('Spontaneous or planned...', 'Surprise Me', '🎁', 'Schedule It', '📅', 'spontaneity', 'spicy'),
('Location...', 'Bedroom Only', '🛏️', 'Anywhere Goes', '🌍', 'adventure', 'spicy'),
('Music during...', 'Set the Mood', '🎵', 'Silence is Golden', '🤫', 'ambiance', 'intimate'),
('Candles...', 'Romantic AF', '🕯️', 'Fire Hazard', '🧯', 'ambiance', 'romantic'),
('Morning or night...', 'Rise & Shine', '🌅', 'After Dark', '🌙', 'timing', 'spicy'),
('Quickie or...', 'Fast & Fun', '⚡', 'Take Our Time', '⏰', 'pace', 'spicy'),
('Dirty talk...', 'YES', '🗣️', 'Actions Only', '🤐', 'communication', 'spicy'),
('Eye contact during...', 'Always', '👁️', 'Too Intense', '🙈', 'intensity', 'intimate'),
('Lingerie...', 'Dress Up!', '👙', 'Less is More', '😏', 'attire', 'spicy'),
('Toys...', 'Fun Addition!', '🎮', 'Natural Only', '🌿', 'accessories', 'spicy'),
('Massage first...', 'Foreplay King/Queen', '💆', 'Skip to Main Event', '⏭️', 'foreplay', 'spicy'),
('Shower before...', 'Fresh & Clean', '🧼', 'Spontaneous!', '💨', 'hygiene', 'honest'),
('After...', 'Pillow Talk', '🗣️', 'Pass Out', '😴', 'aftercare', 'intimate'),
('Snacks after...', 'STARVING', '🍕', 'Just Sleep', '😴', 'recovery', 'silly'),
('Who initiates more...', 'ME', '🙋', 'THEM', '🙋‍♂️', 'initiative', 'honest'),
('Teasing...', 'Love It', '😈', 'Get to the Point', '🎯', 'teasing', 'spicy'),
('Biting...', 'Yes Please', '🦷', 'Keep Those Away', '😬', 'intensity', 'spicy'),
('Scratching...', 'Mark Me Up', '💅', 'Gentle Please', '🪶', 'intensity', 'spicy'),
('Hair pulling...', 'Grab It', '💇', 'Hands Off', '🙅', 'intensity', 'spicy'),
('Blindfold...', 'Exciting!', '🙈', 'Need to See', '👀', 'adventure', 'spicy'),
('Handcuffs...', 'Lock Me Up', '🔐', 'Free Hands Only', '🙌', 'adventure', 'spicy'),
('Power dynamic...', 'Take Control', '👑', 'I Lead', '🦁', 'dominance', 'spicy'),
('Noise level...', 'Let It Out', '📢', 'Quiet Mode', '🤫', 'expression', 'spicy'),
('Positions...', 'Classic Favorites', '⭐', 'Always Trying New', '🆕', 'variety', 'spicy'),
('Mirror...', 'Love to Watch', '🪞', 'No Thanks', '🚫', 'visual', 'spicy'),
('Filming...', 'Private Collection', '📱', 'Memory Only', '🧠', 'boundaries', 'spicy'),
('Public risk...', 'Thrill Seeker', '🎢', 'Private Only', '🏠', 'adventure', 'spicy'),
('Office fantasy...', 'Yes Boss', '👔', 'Keep Work Separate', '💼', 'fantasy', 'spicy'),
('Stranger fantasy...', 'Roleplay It', '🎭', 'Only You', '💑', 'fantasy', 'spicy');

-- ROMANTIC & RELATIONSHIP (61-150)
INSERT INTO questions (question_text, option_a_text, option_a_emoji, option_b_text, option_b_emoji, trait_name, category) VALUES
('Valentine''s Day...', 'Go All Out', '💝', 'Overrated', '🙄', 'romance', 'romantic'),
('Anniversary...', 'Grand Gesture', '🎁', 'Quality Time', '⏰', 'celebration', 'romantic'),
('Love letters...', 'Write Them', '✍️', 'Text is Fine', '📱', 'expression', 'romantic'),
('Flowers...', 'Yes Always', '💐', 'Waste of Money', '💸', 'gifts', 'romantic'),
('Jewelry...', 'Love It', '💎', 'Not My Thing', '🤷', 'gifts', 'romantic'),
('Propose with...', 'Flash Mob', '💃', 'Private Moment', '🤫', 'proposal', 'romantic'),
('Wedding size...', 'Huge Party', '🎉', 'Intimate Elopement', '✈️', 'wedding', 'romantic'),
('Honeymoon...', 'Beach Resort', '🏖️', 'Adventure Travel', '🏔️', 'travel', 'romantic'),
('Move in together...', 'ASAP', '🏃', 'Take Our Time', '🐢', 'pace', 'relationship'),
('Pets together...', 'Fur Babies!', '🐕', 'No Extra Responsibilities', '🙅', 'lifestyle', 'relationship'),
('Kids...', 'Yes Please', '👶', 'Maybe Not', '🤔', 'future', 'relationship'),
('Meeting parents...', 'Excited!', '😊', 'Terrified', '😰', 'milestones', 'relationship'),
('Introducing to friends...', 'Show You Off', '🌟', 'Keep Private', '🔒', 'social', 'relationship'),
('Social media official...', 'Post Everything', '📸', 'Keep It Offline', '📵', 'privacy', 'relationship'),
('Couple photos...', 'All the Time', '🤳', 'Rarely', '📷', 'memories', 'romantic'),
('Shared accounts...', 'Everything Shared', '🤝', 'Keep Separate', '🔐', 'boundaries', 'relationship'),
('Phone password...', 'Open Book', '📖', 'Private Please', '🔒', 'trust', 'relationship'),
('Going through phone...', 'Nothing to Hide', '✅', 'Invasion of Privacy', '❌', 'boundaries', 'honest'),
('Exes...', 'Can Be Friends', '🤝', 'Cut Them Off', '✂️', 'boundaries', 'honest'),
('Opposite sex friends...', 'Totally Fine', '👍', 'Makes Me Uncomfortable', '😕', 'trust', 'honest'),
('Girls/Boys night...', 'Have Fun!', '🎉', 'Miss You Already', '🥺', 'independence', 'relationship'),
('Long distance...', 'We Can Do It', '💪', 'Deal Breaker', '🚫', 'commitment', 'relationship'),
('Time apart...', 'Need It', '🧘', 'Always Together', '👫', 'independence', 'relationship'),
('Finances...', 'Combine Everything', '💰', 'Keep Separate', '💳', 'money', 'relationship'),
('Who pays...', 'Split It', '➗', 'Take Turns', '🔄', 'money', 'honest'),
('Expensive gifts...', 'Worth It For You', '💎', 'Save the Money', '🐷', 'gifts', 'romantic'),
('Surprise trip...', 'DREAM', '✈️', 'Need to Plan', '📋', 'spontaneity', 'romantic'),
('Breakfast in bed...', 'So Romantic', '🥞', 'Crumbs in Sheets', '😬', 'romance', 'silly'),
('Couple workout...', 'Motivation!', '💪', 'Need My Space', '🏃', 'fitness', 'lifestyle'),
('Cooking together...', 'Date Night!', '👨‍🍳', 'Too Many Cooks', '🔪', 'activities', 'romantic');

-- OVER THE TOP / WHAAAAT (91-200)
INSERT INTO questions (question_text, option_a_text, option_a_emoji, option_b_text, option_b_emoji, trait_name, category) VALUES
('Celebrity hall pass...', 'Already Have a List', '📝', 'Only You Forever', '💍', 'fantasy', 'over_the_top'),
('Threesome...', 'Maybe...', '👀', 'Just Us Two', '💑', 'boundaries', 'over_the_top'),
('Strip club together...', 'Could Be Fun', '💃', 'Hard Pass', '🙅', 'adventure', 'over_the_top'),
('Skinny dipping...', 'Let''s Go!', '🏊', 'Keep Clothes On', '👗', 'adventure', 'over_the_top'),
('Mile high club...', 'Bucket List', '✈️', 'Too Risky', '😰', 'adventure', 'over_the_top'),
('Car action...', 'Classic', '🚗', 'Too Cramped', '😤', 'adventure', 'over_the_top'),
('Beach at night...', 'Romantic!', '🌊', 'Sand Gets Everywhere', '😫', 'adventure', 'over_the_top'),
('Hotel balcony...', 'Thrill Seeker', '🏨', 'Inside Please', '🚪', 'adventure', 'over_the_top'),
('Changing room...', 'Quickie!', '👗', 'That''s Illegal', '👮', 'adventure', 'over_the_top'),
('Send spicy pics...', 'For Your Eyes Only', '📱', 'Never Ever', '🙅', 'digital', 'spicy'),
('Receive spicy pics...', 'YES PLEASE', '🤤', 'Prefer In Person', '👀', 'digital', 'spicy'),
('Video call spice...', 'Long Distance Solution', '💻', 'Rather Wait', '⏰', 'digital', 'spicy'),
('Matching tattoos...', 'Ride or Die', '🖤', 'Too Permanent', '😬', 'commitment', 'over_the_top'),
('Couple costumes...', 'ICONIC', '🎃', 'Do Our Own Thing', '🦸', 'couple_goals', 'silly'),
('Baby talk to each other...', 'Guilty', '🍼', 'Absolutely Not', '🙅', 'communication', 'silly'),
('Embarrassing nicknames...', 'In Private', '🤫', 'In Public Too', '📢', 'nicknames', 'silly'),
('Finish each other''s...', 'Sentences!', '🗣️', 'Food!', '🍟', 'connection', 'silly'),
('Wear their clothes...', 'All The Time', '👕', 'That''s Mine!', '😤', 'sharing', 'romantic'),
('Smell their worn shirt...', 'Guilty', '👃', 'That''s Weird', '😂', 'attachment', 'silly'),
('Watch them sleep...', 'So Peaceful', '😴', 'Kinda Creepy', '👀', 'love', 'silly'),
('Pop their pimples...', 'Satisfying!', '😌', 'DISGUSTING', '🤢', 'intimacy', 'over_the_top'),
('Bathroom door open...', 'We''re Past That', '🚪', 'NEVER', '🔒', 'boundaries', 'honest'),
('Fart in front of them...', 'True Love', '💨', 'Still Holding It In', '😬', 'comfort', 'silly'),
('Share a toothbrush...', 'In Emergency', '🦷', 'NEVER EVER', '🤮', 'boundaries', 'over_the_top'),
('Lick their face...', 'Playfully!', '👅', 'Get Away From Me', '🏃', 'weird_love', 'over_the_top'),
('Bite their cheek...', 'So Cute I Could Eat', '😤', 'Use Your Words', '🗣️', 'aggression', 'silly'),
('Baby voice to pets...', 'Who''s a Good Boy', '🐕', 'Normal Voice', '🗣️', 'pet_parent', 'silly'),
('Plant parent together...', 'Our Babies!', '🌱', 'They Always Die', '☠️', 'responsibility', 'lifestyle'),
('IKEA test...', 'Passed!', '✅', 'Almost Broke Up', '😅', 'teamwork', 'relationship'),
('Assemble furniture...', 'Read Instructions', '📖', 'Figure It Out', '🔧', 'problem_solving', 'honest');

-- LIFESTYLE & COMPATIBILITY (121-250)
INSERT INTO questions (question_text, option_a_text, option_a_emoji, option_b_text, option_b_emoji, trait_name, category) VALUES
('Alarm clock...', 'First Ring', '⏰', 'Snooze x100', '😴', 'morning', 'lifestyle'),
('Coffee or tea...', 'COFFEE', '☕', 'Tea Please', '🍵', 'drinks', 'lifestyle'),
('Breakfast...', 'Most Important Meal', '🍳', 'Skip It', '🏃', 'eating', 'lifestyle'),
('Meal prep...', 'Organized Life', '📦', 'Spontaneous Eating', '🎲', 'planning', 'lifestyle'),
('Dishes...', 'Right Away', '🧽', 'They Can Soak', '🌊', 'cleaning', 'lifestyle'),
('Bed making...', 'Every Morning', '🛏️', 'What''s The Point', '🤷', 'cleaning', 'lifestyle'),
('Laundry...', 'Folded Immediately', '👕', 'Live From The Pile', '🗑️', 'cleaning', 'lifestyle'),
('Closet...', 'Color Coordinated', '🌈', 'Organized Chaos', '🌪️', 'organization', 'lifestyle'),
('Thermostat...', 'Cold Sleeper', '❄️', 'Warm & Cozy', '🔥', 'comfort', 'lifestyle'),
('Blanket hog...', 'Guilty', '😈', 'Fair Sharer', '🤝', 'sleeping', 'honest'),
('Sleep position...', 'Starfish', '⭐', 'Fetal Position', '🤱', 'sleeping', 'lifestyle'),
('Pillow count...', 'One is Enough', '1️⃣', 'ALL of Them', '🛏️', 'sleeping', 'lifestyle'),
('Fan for sleeping...', 'Need The Noise', '💨', 'Silence', '🤫', 'sleeping', 'lifestyle'),
('Phone before bed...', 'Doom Scrolling', '📱', 'Airplane Mode', '✈️', 'habits', 'lifestyle'),
('Late night snacks...', 'Fridge Raider', '🍕', 'Kitchen Closed', '🚫', 'eating', 'lifestyle'),
('Hungover cure...', 'Greasy Food', '🍔', 'Sleep It Off', '😴', 'recovery', 'lifestyle'),
('Drunk texts...', 'I Love You x100', '💕', 'Phone Hidden', '🔒', 'drinking', 'honest'),
('Party or chill...', 'Turn Up!', '🎉', 'Couch Potato', '🛋️', 'social', 'lifestyle'),
('Friend group size...', 'Huge Squad', '👥', 'Small Circle', '⭕', 'social', 'lifestyle'),
('Introvert or extrovert...', 'Need My People', '🎊', 'Recharge Alone', '🔋', 'personality', 'lifestyle'),
('Road trip...', 'Driver', '🚗', 'DJ & Snack Master', '🎵', 'travel', 'lifestyle'),
('Flying...', 'Window Seat', '🪟', 'Aisle Access', '🚶', 'travel', 'lifestyle'),
('Vacation style...', 'Adventure!', '🏔️', 'All Inclusive', '🏖️', 'travel', 'lifestyle'),
('Packing...', 'Week Before', '📅', 'Night Before', '🌙', 'planning', 'lifestyle'),
('GPS voice...', 'Follow It', '🗺️', 'I Know Better', '🧠', 'driving', 'lifestyle'),
('Ask for directions...', 'Never Lost', '🧭', 'Too Proud', '😤', 'driving', 'honest'),
('Driving speed...', 'Speed Demon', '🏎️', 'Grandma Mode', '🐢', 'driving', 'lifestyle'),
('Passenger seat...', 'Backseat Driver', '🗣️', 'I Trust You', '😌', 'driving', 'honest'),
('Music in car...', 'Sing Along!', '🎤', 'Podcast Person', '🎧', 'driving', 'lifestyle'),
('Aux cord...', 'Fight For It', '⚔️', 'You Choose', '🎶', 'music', 'lifestyle');

-- MORE SPICY SCENARIOS (151-300)
INSERT INTO questions (question_text, option_a_text, option_a_emoji, option_b_text, option_b_emoji, trait_name, category) VALUES
('Outfit request...', 'Dress Up For You', '👔', 'Wear What I Want', '👗', 'requests', 'spicy'),
('Undressing...', 'Do It For Me', '😏', 'I Got This', '💪', 'intimacy', 'spicy'),
('First thing off...', 'Shoes', '👟', 'Shirt', '👕', 'undressing', 'spicy'),
('Socks during...', 'Always Cold', '🧦', 'Fully Naked', '🔥', 'comfort', 'spicy'),
('Jewelry stays...', 'On', '💍', 'Off', '📴', 'details', 'spicy'),
('Hair...', 'Tie It Up', '👱‍♀️', 'Let It Loose', '💇', 'style', 'spicy'),
('Glasses on...', 'Can''t See Without', '👓', 'Off For Action', '👀', 'practical', 'spicy'),
('Location preference...', 'Bed', '🛏️', 'Couch', '🛋️', 'location', 'spicy'),
('Kitchen counter...', 'Why Not', '🍳', 'That''s For Food', '🍽️', 'location', 'spicy'),
('Washing machine...', 'Good Vibrations', '🧺', 'Strange Idea', '🤔', 'location', 'over_the_top'),
('Against the wall...', 'Hot', '🔥', 'Back Problems', '😅', 'positions', 'spicy'),
('Standing up...', 'Workout!', '💪', 'Lay Me Down', '🛏️', 'positions', 'spicy'),
('On top...', 'Take Control', '👑', 'Prefer Bottom', '⬇️', 'positions', 'spicy'),
('From behind...', 'Classic', '🔙', 'Eye Contact Please', '👁️', 'positions', 'spicy'),
('69...', 'Multitasking!', '🔢', 'One At A Time', '1️⃣', 'positions', 'spicy'),
('Morning action...', 'Best Alarm Clock', '⏰', 'Brush Teeth First', '🦷', 'timing', 'spicy'),
('Middle of night...', 'Wake Me Up', '😴', 'Need My Sleep', '💤', 'timing', 'spicy'),
('Afternoon delight...', 'Lunch Break', '🌞', 'Too Awake', '👀', 'timing', 'spicy'),
('Before dinner...', 'Work Up Appetite', '🍽️', 'After Food Coma', '🥱', 'timing', 'spicy'),
('After workout...', 'Already Sweaty', '💦', 'Shower First', '🚿', 'timing', 'spicy'),
('During period...', 'Red Means Go', '🔴', 'Take A Break', '⏸️', 'comfort', 'honest'),
('When stressed...', 'Best Stress Relief', '😌', 'Not In The Mood', '😤', 'coping', 'honest'),
('When sad...', 'Comfort Me', '🤗', 'Leave Me Alone', '😢', 'emotional', 'honest'),
('After fight...', 'Makeup Action', '💋', 'Need Space First', '🧘', 'conflict', 'honest'),
('When sick...', 'Still Down', '🤧', 'Keep Away', '🚫', 'health', 'honest'),
('On vacation...', 'Multiple Times Daily', '🏝️', 'Too Busy Exploring', '🗺️', 'vacation', 'spicy'),
('At their parents house...', 'Quiet Challenge', '🤫', 'ABSOLUTELY NOT', '🙅', 'boundaries', 'over_the_top'),
('With roommates home...', 'Be Quiet', '🤐', 'Wait Till Alone', '⏰', 'boundaries', 'spicy'),
('Drunk intimacy...', 'Fun & Silly', '🍺', 'Prefer Sober', '🧘', 'drinking', 'honest'),
('High intimacy...', 'Enhanced', '🌿', 'Keep It Natural', '🌱', 'substances', 'honest');

-- COMMUNICATION & HONESTY (181-280)
INSERT INTO questions (question_text, option_a_text, option_a_emoji, option_b_text, option_b_emoji, trait_name, category) VALUES
('Body count talk...', 'Open Book', '📖', 'Past Is Past', '🔒', 'history', 'honest'),
('Ex stories...', 'Share Everything', '🗣️', 'Don''t Ask Don''t Tell', '🤐', 'history', 'honest'),
('Fantasies...', 'Tell Each Other', '💭', 'Keep Private', '🤫', 'desires', 'spicy'),
('Watch adult content...', 'Together Sometimes', '👀', 'Not Our Thing', '🚫', 'media', 'spicy'),
('Describe what you like...', 'Communicate!', '📢', 'Figure It Out', '🔍', 'communication', 'spicy'),
('Feedback during...', 'Yes Right There', '🎯', 'Silent Signals', '👌', 'communication', 'spicy'),
('Tell me what to do...', 'Love Directions', '🗺️', 'Go With Flow', '🌊', 'communication', 'spicy'),
('Safe word...', 'Have One Ready', '🛑', 'Won''t Need It', '💪', 'boundaries', 'spicy'),
('Check in during...', 'You Good?', '✅', 'Read Body Language', '👀', 'consent', 'intimate'),
('Rate the session...', 'Give Notes!', '📝', 'All Great', '⭐', 'feedback', 'honest'),
('Try new things...', 'Always Exploring', '🧭', 'Stick To Favorites', '⭐', 'adventure', 'spicy'),
('Watch tutorials...', 'Research Mode', '🔬', 'Natural Talent', '🌟', 'learning', 'spicy'),
('Read about it...', 'Self Improvement', '📚', 'Just Do It', '✔️', 'learning', 'spicy'),
('Kink quiz together...', 'Fun Date Night', '📊', 'Already Know', '🧠', 'exploration', 'spicy'),
('Bucket list...', 'Written Down', '📝', 'Mental Notes', '🧠', 'planning', 'spicy'),
('New position...', 'Let''s Try!', '🆕', 'If It Works...', '👍', 'adventure', 'spicy'),
('Costume request...', 'Halloween Every Night', '🎃', 'Just You', '💑', 'roleplay', 'spicy'),
('Character play...', 'Full Performance', '🎭', 'Too Awkward', '😅', 'roleplay', 'spicy'),
('Accent roleplay...', 'G''day Mate', '🇦🇺', 'Just My Voice', '🗣️', 'roleplay', 'silly'),
('Teacher/Student...', 'I''ve Been Bad', '😈', 'Keep School Out', '🏫', 'roleplay', 'spicy'),
('Boss/Employee...', 'Overtime', '💼', 'HR Violation', '📋', 'roleplay', 'spicy'),
('Doctor/Patient...', 'Check Up Time', '🩺', 'Not Clinical', '🏥', 'roleplay', 'spicy'),
('Stranger roleplay...', 'What''s Your Name', '🎭', 'I Know It''s You', '😂', 'roleplay', 'spicy'),
('Celebrity impression...', 'Oscar Worthy', '🏆', 'Just Be You', '💕', 'roleplay', 'silly'),
('Dominant or...', 'Take Charge', '👑', 'Be Taken Care Of', '🥰', 'power', 'spicy'),
('Switch roles...', 'Variety!', '🔄', 'Know My Lane', '🛣️', 'power', 'spicy'),
('Use their name...', 'Say It', '📢', 'Pet Names Only', '💕', 'names', 'intimate'),
('Moaning their name...', 'So Hot', '🔥', 'Feels Weird', '😅', 'expression', 'spicy'),
('Talk after...', 'Debrief', '🗣️', 'Just Cuddle', '🤗', 'aftercare', 'intimate'),
('Fall asleep after...', 'Instant KO', '😴', 'Wide Awake', '👀', 'recovery', 'honest');

-- DATE IDEAS & ACTIVITIES (211-350)
INSERT INTO questions (question_text, option_a_text, option_a_emoji, option_b_text, option_b_emoji, trait_name, category) VALUES
('Perfect date...', 'Fancy Dinner', '🍽️', 'Adventure Activity', '🎢', 'dating', 'romantic'),
('Stay in date...', 'Cook Together', '👨‍🍳', 'Order In', '🍕', 'dating', 'romantic'),
('Movie date...', 'Theater Experience', '🎬', 'Home Cinema', '🛋️', 'dating', 'romantic'),
('Horror movie reaction...', 'Grab You Tight', '😱', 'Laugh At It', '😂', 'movies', 'dating'),
('Rom-com...', 'Guilty Pleasure', '💕', 'Cringe', '😬', 'movies', 'dating'),
('Action movie...', 'Hell Yeah', '💥', 'Too Loud', '🔇', 'movies', 'dating'),
('Documentary...', 'Learn Together', '🧠', 'Rather Fiction', '📚', 'movies', 'dating'),
('Reality TV...', 'Trash TV Queen', '👑', 'Brain Rot', '🧟', 'tv', 'lifestyle'),
('Sports together...', 'Team Spirit!', '⚽', 'Rather Not', '😴', 'activities', 'lifestyle'),
('Workout date...', 'Couples Gains', '💪', 'Separate Gym Time', '🏋️', 'fitness', 'lifestyle'),
('Yoga together...', 'Namaste', '🧘', 'Too Peaceful', '😴', 'fitness', 'lifestyle'),
('Dance class...', 'Salsa Night!', '💃', 'Two Left Feet', '🦶', 'activities', 'romantic'),
('Cooking class...', 'Learn Together', '👨‍🍳', 'Figure It Out', '🔪', 'activities', 'romantic'),
('Paint night...', 'So Fun!', '🎨', 'Not Artistic', '🖌️', 'activities', 'romantic'),
('Wine tasting...', 'Sophisticated', '🍷', 'Just Drink It', '🍺', 'activities', 'romantic'),
('Game night...', 'Competitive!', '🎮', 'Sore Loser', '😤', 'activities', 'silly'),
('Board games...', 'Strategy Time', '🎲', 'Takes Too Long', '⏰', 'activities', 'silly'),
('Card games...', 'Poker Face', '🃏', 'Can''t Bluff', '😅', 'activities', 'silly'),
('Video games...', 'Gamer Couple', '🎮', 'Rather Watch', '👀', 'activities', 'lifestyle'),
('Escape room...', 'Team Genius', '🧩', 'Too Stressful', '😰', 'activities', 'dating'),
('Karaoke...', 'Duet Time!', '🎤', 'Stage Fright', '😨', 'activities', 'silly'),
('Concert...', 'Front Row!', '🎸', 'Back Vibes', '🎶', 'activities', 'dating'),
('Festival...', 'Full Weekend', '🎪', 'Too Crowded', '👥', 'activities', 'dating'),
('Museum date...', 'Art Lovers', '🖼️', 'Kinda Boring', '🥱', 'activities', 'romantic'),
('Zoo date...', 'So Cute!', '🐼', 'Animals Smell', '👃', 'activities', 'dating'),
('Beach date...', 'Paradise!', '🏖️', 'Sand Everywhere', '😫', 'activities', 'dating'),
('Picnic...', 'So Romantic', '🧺', 'Bugs', '🐜', 'activities', 'romantic'),
('Hiking...', 'Nature Lovers', '🥾', 'Why Walk', '🚗', 'activities', 'lifestyle'),
('Camping...', 'Under the Stars', '⛺', 'Hotel Please', '🏨', 'activities', 'lifestyle'),
('Staycation...', 'Home Spa', '🛁', 'Go Somewhere!', '✈️', 'activities', 'lifestyle');

-- PERSONALITY & QUIRKS (241-400)
INSERT INTO questions (question_text, option_a_text, option_a_emoji, option_b_text, option_b_emoji, trait_name, category) VALUES
('Arguing style...', 'Talk It Out', '🗣️', 'Need Space First', '🚪', 'conflict', 'honest'),
('Say sorry first...', 'Even If Not Wrong', '🙏', 'Only When Wrong', '⚖️', 'conflict', 'honest'),
('Hold grudges...', 'Forgive & Forget', '💕', 'Remember Everything', '🐘', 'conflict', 'honest'),
('Bring up past fights...', 'Clean Slate', '🧹', 'Evidence Folder', '📁', 'conflict', 'honest'),
('Silent treatment...', 'Never', '❌', 'Sometimes', '😶', 'conflict', 'honest'),
('Cry during fights...', 'Very Emotional', '😢', 'Stay Composed', '😐', 'emotional', 'honest'),
('Apologize with...', 'Words', '💬', 'Actions', '🎁', 'apology', 'honest'),
('Makeup after fight...', 'Talk Then Physical', '💋', 'Physical Then Talk', '🔥', 'conflict', 'spicy'),
('Admit when wrong...', 'Easily', '✋', 'Stubborn', '🐂', 'honest', 'honest'),
('Compromise...', 'Meet in Middle', '🤝', 'Stand Ground', '🏔️', 'relationship', 'honest'),
('Support vs solve...', 'Just Listen', '👂', 'Fix It Mode', '🔧', 'support', 'honest'),
('Venting...', 'Let Me Rant', '😤', 'Give Advice', '💡', 'support', 'honest'),
('When they''re sad...', 'Hold Them', '🤗', 'Give Space', '🚪', 'support', 'romantic'),
('Cheer them up...', 'Make Them Laugh', '😂', 'Let Them Feel', '💭', 'support', 'honest'),
('Surprise gifts...', 'Love Giving', '🎁', 'Just Ask What', '🤷', 'gifts', 'romantic'),
('Gift receiving...', 'Love Surprises', '🎉', 'Share Wishlist', '📝', 'gifts', 'romantic'),
('Remember dates...', 'Calendar Alert', '📅', 'Naturally', '🧠', 'memory', 'relationship'),
('Anniversary month...', 'Celebrate All Month', '🎊', 'Just The Day', '📆', 'celebration', 'romantic'),
('Birthday expectations...', 'Go Big', '🎂', 'Low Key', '🤫', 'celebration', 'honest'),
('Surprise party...', 'LOVE', '🎉', 'Hate Surprises', '😰', 'celebration', 'honest'),
('Plan hangouts...', 'Social Director', '📋', 'Go With Flow', '🌊', 'social', 'lifestyle'),
('Cancel plans...', 'Feel Guilty', '😔', 'Self Care!', '🛁', 'social', 'honest'),
('Meet new people...', 'Excited!', '🤗', 'Anxious', '😰', 'social', 'honest'),
('Small talk...', 'Natural', '🗣️', 'Painful', '😬', 'social', 'honest'),
('Deep conversations...', 'Crave Them', '🧠', 'Keep It Light', '☀️', 'social', 'honest'),
('Gossip...', 'Tell Me Everything', '👀', 'Not My Business', '🙅', 'social', 'honest'),
('Share everything...', 'No Secrets', '📖', 'Some Privacy', '🔐', 'privacy', 'honest'),
('Phone unlocked...', 'Nothing to Hide', '🔓', 'Need Privacy', '🔒', 'privacy', 'honest'),
('Location sharing...', 'Always On', '📍', 'That''s Creepy', '👀', 'privacy', 'honest'),
('Social media stalking...', 'Deep Dive', '🕵️', 'Trust Issues', '😅', 'digital', 'honest');

-- FUTURE & SERIOUS (271-400)
INSERT INTO questions (question_text, option_a_text, option_a_emoji, option_b_text, option_b_emoji, trait_name, category) VALUES
('Marriage...', 'Can''t Wait!', '💍', 'Piece of Paper', '📄', 'future', 'relationship'),
('Wedding venue...', 'Destination', '✈️', 'Hometown', '🏠', 'wedding', 'romantic'),
('Proposal style...', 'Public & Grand', '🎆', 'Private & Intimate', '🕯️', 'proposal', 'romantic'),
('Engagement length...', 'Short & Sweet', '⚡', 'Take Time to Plan', '📅', 'wedding', 'relationship'),
('Prenup...', 'Smart Planning', '📋', 'Trust Issues', '😕', 'future', 'honest'),
('Last name...', 'Take Theirs', '💕', 'Keep Mine', '💪', 'identity', 'relationship'),
('Hyphenate names...', 'Best of Both', '➕', 'Too Complicated', '😵', 'identity', 'relationship'),
('Kids timeline...', 'ASAP', '👶', 'Way Later', '⏳', 'future', 'relationship'),
('Number of kids...', 'Full House', '👨‍👩‍👧‍👦', 'One and Done', '1️⃣', 'future', 'relationship'),
('Parenting style...', 'Strict Love', '📏', 'Cool Parent', '😎', 'future', 'relationship'),
('Pet parent first...', 'Fur Babies!', '🐕', 'Human Babies', '👶', 'future', 'lifestyle'),
('Dog or cat...', 'Doggo', '🐕', 'Kitty', '🐱', 'pets', 'lifestyle'),
('Where to live...', 'City Life', '🌆', 'Suburbs/Country', '🏡', 'future', 'lifestyle'),
('Dream house...', 'Modern', '🏢', 'Cozy Traditional', '🏠', 'future', 'lifestyle'),
('Home ownership...', 'Buy ASAP', '🏠', 'Rent Freedom', '🔑', 'future', 'lifestyle'),
('Retirement plan...', 'Early Retire', '🏖️', 'Work Forever', '💼', 'future', 'lifestyle'),
('Travel in retirement...', 'See The World', '🌍', 'Stay Home', '🏠', 'future', 'lifestyle'),
('Grow old together...', 'Matching Rockers', '🪑', 'Stay Young Forever', '🧒', 'future', 'romantic'),
('In sickness...', 'By Your Side', '🤒', 'Call A Nurse', '👩‍⚕️', 'commitment', 'relationship'),
('Through thick and thin...', 'Always', '💪', 'Depends', '🤔', 'commitment', 'honest'),
('Move for their job...', 'Anywhere Together', '🌍', 'Need Roots', '🌳', 'commitment', 'relationship'),
('Career vs relationship...', 'Balance Both', '⚖️', 'One Priority', '1️⃣', 'priorities', 'honest'),
('Support their dreams...', 'Always', '💫', 'Be Realistic', '📊', 'support', 'relationship'),
('Financial support...', 'What''s Mine is Yours', '💰', 'Earn Your Own', '💪', 'money', 'honest'),
('Stay at home parent...', 'Would Love To', '🏠', 'Need Career', '💼', 'future', 'relationship'),
('Work from home...', 'Together All Day!', '👩‍💻', 'Need Space', '🚪', 'work', 'lifestyle'),
('Office vs remote...', 'Home Office', '🏠', 'Need People', '👥', 'work', 'lifestyle'),
('Workaholic...', 'Hustle Mode', '💼', 'Work-Life Balance', '⚖️', 'work', 'lifestyle'),
('Stress handling...', 'Need Support', '🤗', 'Need Space', '🧘', 'coping', 'honest'),
('Life goals...', 'Aligned', '🎯', 'Figure It Out', '🤷', 'future', 'relationship');

-- WILD SCENARIOS & HYPOTHETICALS (301-500)
INSERT INTO questions (question_text, option_a_text, option_a_emoji, option_b_text, option_b_emoji, trait_name, category) VALUES
('Caught by parents...', 'Hide Under Covers', '🙈', 'Own It', '😎', 'embarrassment', 'over_the_top'),
('Walked in on...', 'Lock The Door!', '🔒', 'Keep Going', '😈', 'embarrassment', 'over_the_top'),
('Neighbors heard...', 'Mortified', '😳', 'Good For Them', '💪', 'noise', 'over_the_top'),
('Left evidence...', 'Clean Up Crew', '🧹', 'Oops', '🤷', 'mess', 'over_the_top'),
('Forgot name during...', 'Never', '🙅', 'It Happens', '😬', 'embarrassment', 'over_the_top'),
('Wrong name slip...', 'Relationship Over', '💀', 'We''ll Laugh', '😂', 'embarrassment', 'over_the_top'),
('Weird noise made...', 'Pretend Nothing', '🙈', 'Laugh It Off', '😂', 'embarrassment', 'silly'),
('Fell off bed...', 'Keep Going', '💪', 'Mood Ruined', '😅', 'accidents', 'silly'),
('Cramp happened...', 'Push Through', '😤', 'Take A Break', '⏸️', 'accidents', 'silly'),
('Pet walked in...', 'They''ve Seen Things', '🐕', 'Put Them Out', '🚪', 'interruptions', 'silly'),
('Phone rang during...', 'Ignore It', '📵', 'Might Be Important', '📱', 'interruptions', 'honest'),
('Doorbell rang...', 'They Can Wait', '🚪', 'Pause & Check', '⏸️', 'interruptions', 'honest'),
('Fire alarm...', 'It''s Fine', '🔥', 'Safety First', '🧯', 'interruptions', 'silly'),
('Power went out...', 'Even Better', '🕯️', 'Need To See', '💡', 'adaptability', 'spicy'),
('AC broke...', 'Getting Hot Anyway', '🥵', 'Too Sweaty', '💦', 'adaptability', 'spicy'),
('Bed broke...', 'Badge of Honor', '🏆', 'Need New Bed', '🛏️', 'accidents', 'over_the_top'),
('Headboard noise...', 'Let Them Know', '📢', 'Add Padding', '🔇', 'noise', 'spicy'),
('Squeaky bed...', 'Music Cover', '🎵', 'Floor Time', '😏', 'adaptability', 'spicy'),
('Roommate returned early...', 'Continue Quietly', '🤫', 'Abort Mission', '🚨', 'boundaries', 'over_the_top'),
('Their ex texted during...', 'Don''t Check', '📵', 'Who''s That', '👀', 'trust', 'over_the_top'),
('Thought of ex during...', 'Never!', '🙅', 'Brain Does Things', '🧠', 'honesty', 'over_the_top'),
('Fantasy about someone else...', 'Normal', '🤷', 'Only You', '💕', 'fantasy', 'honest'),
('Celebrity fantasy...', 'Don''t Tell', '🤐', 'Share It', '🗣️', 'fantasy', 'honest'),
('Friend attraction...', 'Eyes Wander', '👀', 'Blind To Others', '😇', 'attraction', 'honest'),
('If you were single...', 'Miss The Game', '🎮', 'Happy With You', '💕', 'commitment', 'honest'),
('Regret past hookups...', 'They Made Me Me', '🦋', 'Wish I Waited', '⏳', 'history', 'honest'),
('Tell me your number...', 'Honest', '📊', 'Who''s Counting', '🤷', 'history', 'honest'),
('Judge their number...', 'Past Is Past', '⏪', 'A Little...', '🤔', 'judgment', 'honest'),
('Compared to exes...', 'You''re The Best', '🏆', 'Don''t Compare', '🙅', 'comparison', 'romantic'),
('Learned from exes...', 'Experience Helps', '📚', 'Rather Not Think', '🙈', 'history', 'honest');

-- MORE SPICY PREFERENCES (331-450)
INSERT INTO questions (question_text, option_a_text, option_a_emoji, option_b_text, option_b_emoji, trait_name, category) VALUES
('Preferred pace...', 'Slow & Sensual', '🐢', 'Fast & Passionate', '🐆', 'pace', 'spicy'),
('Duration preference...', 'Marathon', '🏃', 'Sprint', '⚡', 'duration', 'spicy'),
('Frequency ideal...', 'Multiple Daily', '📈', 'Quality > Quantity', '⭐', 'frequency', 'spicy'),
('Dry spell...', 'Going Crazy', '😫', 'Survive It', '💪', 'needs', 'honest'),
('Long distance intimacy...', 'Phone Fun', '📱', 'Wait to Meet', '⏰', 'distance', 'spicy'),
('Reunion after distance...', 'Straight To It', '🏃', 'Catch Up First', '🗣️', 'reunion', 'spicy'),
('After vacation...', 'Vacation Mode Continues', '🏝️', 'Back To Normal', '📋', 'energy', 'spicy'),
('Sunday morning...', 'Stay In Bed', '🛏️', 'Get Things Done', '✅', 'weekend', 'spicy'),
('Lazy day...', 'Multiple Rounds', '🔄', 'Just Chill', '📺', 'lazy', 'spicy'),
('Rainy day...', 'Perfect Weather', '🌧️', 'Gloomy Mood', '😔', 'weather', 'spicy'),
('Snow day...', 'Body Heat', '🔥', 'Too Cold', '❄️', 'weather', 'spicy'),
('Heat wave...', 'Too Sweaty', '💦', 'AC On Max', '❄️', 'weather', 'spicy'),
('After gym...', 'Already Pumped', '💪', 'Need Shower', '🚿', 'fitness', 'spicy'),
('Post-swim...', 'Beach Body Ready', '🏖️', 'Chlorine Hair', '👩', 'activities', 'spicy'),
('After dancing...', 'Energy Keeps Going', '💃', 'Exhausted', '😴', 'activities', 'spicy'),
('Wine drunk...', 'Romantic Mood', '🍷', 'Sleepy', '😴', 'drinking', 'spicy'),
('Beer drunk...', 'Fun & Silly', '🍺', 'Bloated', '🎈', 'drinking', 'honest'),
('Tequila drunk...', 'Wild Card', '🃏', 'Bad Decisions', '🙈', 'drinking', 'over_the_top'),
('Champagne mood...', 'Celebration!', '🥂', 'Bubbles = Burps', '😬', 'drinking', 'silly'),
('High energy...', 'Let''s GO', '⚡', 'Netflix Mode', '📺', 'energy', 'spicy'),
('Low energy...', 'Cuddle Only', '🤗', 'Nap Time', '😴', 'energy', 'romantic'),
('Stressed...', 'Best Stress Relief', '😌', 'Too Much On Mind', '🧠', 'stress', 'honest'),
('Celebrating...', 'Victory Lap', '🏆', 'Dinner First', '🍽️', 'celebration', 'spicy'),
('Bad day...', 'Make Me Feel Better', '🥺', 'Leave Me Alone', '🚪', 'comfort', 'honest'),
('Before travel...', 'One For The Road', '✈️', 'Gotta Pack', '🧳', 'timing', 'spicy'),
('After travel...', 'Missed You', '💋', 'Jet Lagged', '😴', 'timing', 'spicy'),
('Hotel room...', 'VACATION MODE', '🏨', 'Unfamiliar Bed', '😕', 'travel', 'spicy'),
('Airbnb...', 'Someone Else''s Bed', '🛏️', 'Adventure!', '🗺️', 'travel', 'spicy'),
('Tent...', 'Nature Is Romantic', '⛺', 'Need A Bed', '🛏️', 'camping', 'spicy'),
('Car backseat...', 'Throwback', '🚗', 'Not Teenagers', '🙅', 'location', 'spicy');

-- ATTRACTION & PHYSICAL (361-500)
INSERT INTO questions (question_text, option_a_text, option_a_emoji, option_b_text, option_b_emoji, trait_name, category) VALUES
('First noticed...', 'Eyes', '👁️', 'Smile', '😊', 'attraction', 'romantic'),
('Attracted to...', 'Face First', '😍', 'Body First', '💪', 'attraction', 'honest'),
('Height difference...', 'Love It', '📏', 'Same Height', '⚖️', 'preference', 'romantic'),
('Facial hair...', 'Love It', '🧔', 'Clean Shaven', '🪒', 'preference', 'honest'),
('Long hair...', 'Yes Please', '💇', 'Short & Simple', '✂️', 'preference', 'honest'),
('Tattoos...', 'Hot', '🔥', 'Not My Thing', '🤷', 'preference', 'honest'),
('Piercings...', 'Love Them', '💎', 'Natural', '🌿', 'preference', 'honest'),
('Muscles...', 'Gym Bro', '💪', 'Dad Bod', '🐻', 'preference', 'honest'),
('Curves...', 'Absolutely', '🍑', 'All Bodies', '💕', 'preference', 'honest'),
('What you wear to bed...', 'Nothing', '😏', 'Comfy Clothes', '👕', 'sleepwear', 'spicy'),
('Their sleepwear...', 'Less Is More', '🔥', 'Cozy Is Cute', '🧸', 'sleepwear', 'spicy'),
('Morning breath...', 'Kiss Anyway', '💋', 'Brush First', '🦷', 'morning', 'honest'),
('Morning look...', 'Cute Mess', '🥰', 'Need 20 Min', '⏰', 'morning', 'romantic'),
('Makeup preference...', 'Love Glam', '💄', 'Natural Beauty', '🌸', 'appearance', 'honest'),
('Perfume/Cologne...', 'Signature Scent', '👃', 'Natural Smell', '🌿', 'scent', 'romantic'),
('Post-workout smell...', 'Pheromones', '💪', 'Shower First', '🚿', 'scent', 'honest'),
('Hands...', 'Love Holding', '🤝', 'Just Hands', '🤷', 'attraction', 'romantic'),
('Neck...', 'Kiss It', '💋', 'Ticklish', '😆', 'body', 'spicy'),
('Ears...', 'Whisper Zone', '👂', 'Don''t Touch', '🚫', 'body', 'spicy'),
('Back...', 'Scratch It', '💅', 'Massage Only', '💆', 'body', 'spicy'),
('Feet...', 'Rub Them', '🦶', 'Stay Away', '🙅', 'body', 'honest'),
('Ticklish...', 'Very', '😆', 'Not At All', '😐', 'body', 'silly'),
('Most sensitive...', 'Neck', '💋', 'Ears', '👂', 'body', 'spicy'),
('Best feature...', 'I''ll Tell You', '😏', 'You Know', '💕', 'body', 'flirty'),
('Their best feature...', 'Eyes', '👁️', 'Smile', '😊', 'attraction', 'romantic'),
('Undeniable attraction...', 'Their Voice', '🗣️', 'Their Laugh', '😂', 'attraction', 'romantic'),
('Instant turn on...', 'Confidence', '👑', 'Kindness', '💕', 'attraction', 'romantic'),
('Instant turn off...', 'Arrogance', '😤', 'Bad Hygiene', '🤢', 'attraction', 'honest'),
('Deal breaker...', 'Cheating', '💔', 'Lying', '🤥', 'boundaries', 'honest'),
('Green flag...', 'Good Listener', '👂', 'Makes Me Laugh', '😂', 'attraction', 'romantic');

-- FUN & SILLY (391-550)
INSERT INTO questions (question_text, option_a_text, option_a_emoji, option_b_text, option_b_emoji, trait_name, category) VALUES
('Pineapple on pizza...', 'Delicious!', '🍕', 'Abomination', '🤮', 'food', 'silly'),
('Toilet paper...', 'Over', '📜', 'Under', '🧻', 'preference', 'silly'),
('Squeeze toothpaste...', 'From Bottom', '⬇️', 'Middle Chaos', '🌪️', 'habits', 'silly'),
('Shower temp...', 'Scalding Hot', '🔥', 'Cold Shock', '❄️', 'shower', 'lifestyle'),
('Wet towel on bed...', 'Acceptable', '😌', 'Crime', '🚔', 'habits', 'silly'),
('Dishes in sink...', 'They''ll Wait', '🍽️', 'Wash Immediately', '🧽', 'cleaning', 'lifestyle'),
('Make bed...', 'Every Day', '🛏️', 'Why Bother', '🤷', 'habits', 'lifestyle'),
('Shoes in house...', 'Take Off!', '👟', 'Keep On', '🚶', 'habits', 'lifestyle'),
('Fan on in winter...', 'Need Circulation', '💨', 'Too Cold', '❄️', 'comfort', 'lifestyle'),
('Sleep with TV on...', 'Background Noise', '📺', 'Complete Dark', '🌑', 'sleep', 'lifestyle'),
('Separate blankets...', 'Life Hack', '💡', 'Share One', '🤗', 'sleeping', 'lifestyle'),
('Snoring...', 'Wear Earplugs', '👂', 'Elbow Them', '💪', 'sleeping', 'honest'),
('Sleep talking...', 'What Did I Say?', '😳', 'I''m Quiet', '🤫', 'sleeping', 'silly'),
('Early bird or night owl...', 'Sunrise', '🌅', 'Midnight', '🌙', 'schedule', 'lifestyle'),
('Nap person...', 'Power Napper', '😴', 'Can''t Nap', '😳', 'sleep', 'lifestyle'),
('Food in bed...', 'Snack Time', '🍿', 'Crumb Phobia', '😤', 'eating', 'lifestyle'),
('Phone usage in bed...', 'Doom Scroll', '📱', 'Screen Free Zone', '📵', 'habits', 'lifestyle'),
('Last one to sleep...', 'Usually Me', '🦉', 'Out First', '😴', 'schedule', 'lifestyle'),
('First one up...', 'Early Riser', '🌅', 'Need Alarm x10', '⏰', 'schedule', 'lifestyle'),
('Weekend alarm...', 'No Alarms!', '🙅', 'Same Schedule', '⏰', 'schedule', 'lifestyle'),
('Caffeine after noon...', 'Need It', '☕', 'Can''t Sleep', '😵', 'habits', 'lifestyle'),
('Midnight snack...', 'Fridge Raider', '🌙', 'Kitchen Closed', '🚫', 'eating', 'lifestyle'),
('Talk in morning...', 'Chatty', '🗣️', 'Need Coffee First', '☕', 'morning', 'lifestyle'),
('Grumpy when hungry...', 'Hangry Monster', '👹', 'I''m Fine', '😇', 'eating', 'honest'),
('Eating speed...', 'Inhale Food', '💨', 'Savor It', '😌', 'eating', 'lifestyle'),
('Last bite...', 'Give To You', '🥺', 'Fight For It', '⚔️', 'sharing', 'romantic'),
('Sharing food...', 'What''s Mine Is Yours', '🍟', 'Order Your Own', '😤', 'sharing', 'honest'),
('Try each other''s food...', 'Always', '🍝', 'I Know What I Want', '🎯', 'sharing', 'lifestyle'),
('Cook or cleanup...', 'Cook!', '👨‍🍳', 'Cleanup!', '🧽', 'chores', 'lifestyle'),
('Grocery shopping...', 'Love It', '🛒', 'Boring', '😴', 'chores', 'lifestyle');

-- ADVENTUROUS & BUCKET LIST (421-600)
INSERT INTO questions (question_text, option_a_text, option_a_emoji, option_b_text, option_b_emoji, trait_name, category) VALUES
('Skydiving together...', 'BUCKET LIST', '🪂', 'Hard Pass', '🙅', 'adventure', 'lifestyle'),
('Bungee jumping...', 'Thrill Seeker', '🎢', 'Nope', '😰', 'adventure', 'lifestyle'),
('Scuba diving...', 'Under The Sea', '🐠', 'Stay Dry', '🏖️', 'adventure', 'lifestyle'),
('Road trip across country...', 'Let''s Go!', '🚗', 'Fly There', '✈️', 'travel', 'lifestyle'),
('Backpacking...', 'Adventure!', '🎒', 'Suitcase Life', '🧳', 'travel', 'lifestyle'),
('Couples massage...', 'So Relaxing', '💆', 'Rather Alone', '🧘', 'activities', 'romantic'),
('Hot tub together...', 'Romantic', '🛁', 'Public Soup', '🍲', 'activities', 'spicy'),
('Sauna together...', 'Sweat Together', '🥵', 'Too Hot', '🔥', 'activities', 'spicy'),
('Skinny dipping...', 'Liberating!', '🏊', 'Keep Clothes', '👙', 'adventure', 'over_the_top'),
('Nude beach...', 'Why Not', '🏖️', 'Never Ever', '🙅', 'adventure', 'over_the_top'),
('Couples boudoir...', 'Spicy Memories', '📸', 'Too Vulnerable', '😬', 'adventure', 'spicy'),
('Paint each other...', 'Body Art', '🎨', 'Messy', '🎨', 'activities', 'spicy'),
('Food play...', 'Strawberries & Cream', '🍓', 'Food Is For Eating', '🍽️', 'spicy', 'spicy'),
('Ice cubes...', 'Temperature Play', '🧊', 'Too Cold', '❄️', 'spicy', 'spicy'),
('Whipped cream...', 'Classic', '🍦', 'Sticky Mess', '😬', 'spicy', 'spicy'),
('Chocolate sauce...', 'Dessert Time', '🍫', 'Ants', '🐜', 'spicy', 'spicy'),
('Body shots...', 'Party Mode', '🥃', 'Rather Not', '🤷', 'drinking', 'over_the_top'),
('Truth or dare...', 'Dare!', '🎲', 'Truth', '🤔', 'games', 'spicy'),
('Strip poker...', 'Deal Me In', '🃏', 'Can''t Play Poker', '😅', 'games', 'spicy'),
('Spin the bottle...', 'Nostalgic', '🍾', 'Just Us', '💑', 'games', 'silly'),
('Seven minutes...', 'Need More Time', '⏰', 'Enough', '✅', 'games', 'spicy'),
('Never have I ever...', 'Spill Tea!', '🍵', 'Some Secrets', '🤫', 'games', 'honest'),
('Two truths one lie...', 'Good At This', '🧠', 'Bad Liar', '😇', 'games', 'silly'),
('Would you rather...', 'Spicy Version', '🌶️', 'PG Version', '👶', 'games', 'spicy'),
('Couples game night...', 'Competitive!', '🏆', 'Casual Fun', '🎯', 'games', 'silly'),
('Double date...', 'So Fun!', '👯', 'Rather Just Us', '💑', 'social', 'lifestyle'),
('Group vacation...', 'Party!', '🎉', 'Couple Trip', '✈️', 'social', 'lifestyle'),
('Swingers party...', 'Curious', '👀', 'No Thank You', '🙅', 'boundaries', 'over_the_top'),
('Clothing optional resort...', 'Freedom!', '🏝️', 'Keep Covered', '👙', 'boundaries', 'over_the_top'),
('Fantasy island...', 'Let''s Go!', '🏝️', 'Home Is Fine', '🏠', 'adventure', 'over_the_top');

-- DEEP & MEANINGFUL (451-600)
INSERT INTO questions (question_text, option_a_text, option_a_emoji, option_b_text, option_b_emoji, trait_name, category) VALUES
('Love at first sight...', 'Believer', '💕', 'Love Grows', '🌱', 'romance', 'romantic'),
('Soulmates...', 'The One', '💫', 'Many Matches', '🎯', 'romance', 'romantic'),
('Fate or choice...', 'Meant To Be', '✨', 'We Choose This', '🤝', 'philosophy', 'romantic'),
('Love changes people...', 'Grows You', '🌳', 'Stay Yourself', '💪', 'growth', 'honest'),
('I love you first...', 'Said It', '🥺', 'Waited', '⏳', 'vulnerability', 'romantic'),
('How often say I love you...', 'Constantly', '💕', 'When Meaningful', '💝', 'expression', 'romantic'),
('Love languages...', 'Match Perfectly', '💑', 'Learning Each Other', '📚', 'compatibility', 'romantic'),
('Express love how...', 'Words', '💬', 'Actions', '🎁', 'expression', 'romantic'),
('Feel most loved when...', 'Quality Time', '⏰', 'Physical Touch', '🤗', 'receiving', 'romantic'),
('Jealousy is...', 'Sign Of Love', '💕', 'Insecurity', '😕', 'emotions', 'honest'),
('Trust is earned or given...', 'Earned', '📈', 'Given First', '🤝', 'trust', 'honest'),
('Forgive easily...', 'Big Heart', '❤️', 'Takes Time', '⏳', 'forgiveness', 'honest'),
('Forget easily...', 'Move On', '➡️', 'Remember Everything', '🐘', 'memory', 'honest'),
('Biggest sacrifice for love...', 'Anything', '💕', 'Healthy Boundaries', '🚧', 'commitment', 'honest'),
('Long distance could work...', 'Love Conquers', '💪', 'Need Presence', '🤗', 'commitment', 'honest'),
('Relationship goal...', 'Best Friends', '🤝', 'Passionate Lovers', '🔥', 'goals', 'romantic'),
('Marriage goal...', 'Forever', '💍', 'Day By Day', '📅', 'commitment', 'relationship'),
('Grow old together...', 'Can''t Wait', '👵👴', 'Stay Young Forever', '🧒', 'future', 'romantic'),
('How did we meet story...', 'Tell Everyone', '📢', 'Keep Private', '🤫', 'memories', 'romantic'),
('Our love story is...', 'Fairy Tale', '👸🤴', 'Real & Messy', '❤️‍🩹', 'perspective', 'romantic'),
('When knew I loved you...', 'Instantly', '⚡', 'Slowly Realized', '🌅', 'love', 'romantic'),
('What I love most...', 'Your Heart', '❤️', 'Your Mind', '🧠', 'attraction', 'romantic'),
('Why you chose me...', 'No Choice', '💫', 'Every Day Choose', '🤝', 'commitment', 'romantic'),
('Relationship secret...', 'Communication', '🗣️', 'Physical Connection', '💋', 'success', 'relationship'),
('Fight for us...', 'Always', '⚔️', 'Know When To Rest', '🏳️', 'commitment', 'relationship'),
('Distance makes heart...', 'Grow Fonder', '💕', 'Wander', '👀', 'distance', 'honest'),
('Time apart is...', 'Healthy', '🌿', 'Painful', '💔', 'independence', 'honest'),
('Missing you is...', 'Sweet Torture', '🥺', 'Motivation To Reunite', '🏃', 'separation', 'romantic'),
('Without you I...', 'Incomplete', '🧩', 'Whole But Happier With', '💕', 'independence', 'romantic'),
('You complete me...', 'Yes!', '💝', 'We Complement', '🤝', 'perspective', 'romantic');
