-- More spicy/fun Gen-Z questions to reach 1000+
-- Categories: flirty, romantic, spicy, intimate, over_the_top, silly, honest, lifestyle

INSERT INTO questions (question_text, option_a_text, option_a_emoji, option_b_text, option_b_emoji, trait_name, category) VALUES

-- SPICY DATING VIBES
('First date energy...', 'Nervous wreck', '😰', 'Main character', '💅', 'confidence', 'flirty'),
('When they text "wyd"...', 'Overthink for 20min', '🤔', 'Instant reply', '⚡', 'texting', 'flirty'),
('Flirting style be like...', 'Eye contact only', '👀', 'Straight up say it', '🗣️', 'approach', 'flirty'),
('When the vibe is off...', 'Ghost immediately', '👻', 'Talk it out', '💬', 'conflict', 'honest'),
('Relationship green flag...', 'Remembers details', '🧠', 'Physical touch', '🤗', 'love_language', 'romantic'),
('Deal breaker energy...', 'Bad hygiene', '🦨', 'Rude to waiters', '😤', 'standards', 'honest'),
('First kiss timing...', 'First date or bust', '😘', 'Wait for the moment', '✨', 'pace', 'romantic'),
('Love confession style...', 'Grand gesture', '🎭', 'Casual mention', '😎', 'expression', 'romantic'),
('When they don''t text back...', 'Spiral', '🌀', 'Unbothered king', '👑', 'attachment', 'honest'),
('Meeting the parents...', 'Bring flowers', '💐', 'Wing it', '🦋', 'preparation', 'lifestyle'),

-- BEDROOM ENERGY (SPICY BUT TASTEFUL)
('Music during...', 'Absolutely yes', '🎵', 'Silence is golden', '🤫', 'ambiance', 'spicy'),
('Candles or nah...', 'Full spa vibes', '🕯️', 'Normal lights fine', '💡', 'setting', 'spicy'),
('Morning or night...', 'Sunrise energy', '🌅', 'After dark only', '🌙', 'timing', 'spicy'),
('Spontaneous or planned...', 'Calendar it', '📅', 'Surprise me', '🎁', 'style', 'spicy'),
('Talk about it or...', 'Communication king', '👑', 'Actions speak', '🎬', 'communication', 'spicy'),
('Try new things...', 'Adventure mode ON', '🗺️', 'Comfort zone please', '🛋️', 'openness', 'spicy'),
('Who initiates...', 'Always me', '🙋', 'Take turns', '🔄', 'dynamic', 'spicy'),
('Post-activity vibes...', 'Cuddle required', '🤗', 'Personal space', '🚀', 'aftercare', 'spicy'),
('PDA energy...', 'Get a room', '🏨', 'Keep it private', '🔒', 'public', 'spicy'),
('Compliments during...', 'Words of affirmation', '💬', 'Show don''t tell', '🎭', 'feedback', 'spicy'),

-- CHAOTIC RELATIONSHIP MOMENTS
('They ate your leftovers...', 'War crime', '⚔️', 'It''s just food', '🤷', 'sharing', 'silly'),
('Netflix and...', 'Actually watch', '📺', 'Who''s watching', '😏', 'intent', 'spicy'),
('Sharing passwords...', 'Full access', '🔓', 'Privacy matters', '🔐', 'trust', 'honest'),
('Their ex liked a pic...', 'Red flag parade', '🚩', 'Who cares', '💅', 'jealousy', 'honest'),
('Matching outfits...', 'Couple goals', '👫', 'Absolutely not', '🙅', 'style', 'silly'),
('Pet names in public...', 'Baby, babe, etc', '🍼', 'First name only', '📛', 'expression', 'romantic'),
('Finish each other''s...', 'Sentences yes', '🗣️', 'Food no touch', '🍕', 'sharing', 'silly'),
('Joint social media...', 'Relationship page', '📱', 'Individual vibes', '🎭', 'boundaries', 'lifestyle'),
('Bathroom door policy...', 'Always open', '🚪', 'Locked forever', '🔒', 'privacy', 'silly'),
('Sharing location...', '24/7 tracking', '📍', 'Trust > tracking', '💝', 'trust', 'honest'),

-- LOVE LANGUAGE CHAOS
('Gift giving...', 'Expensive = love', '💎', 'Thought counts', '💭', 'gifts', 'romantic'),
('Quality time means...', 'Phone down zone', '📵', 'Parallel play ok', '🎮', 'attention', 'romantic'),
('Physical touch need...', 'Constant contact', '🤝', 'Personal bubble', '🫧', 'touch', 'romantic'),
('Words of affirmation...', 'Tell me daily', '📣', 'Actions > words', '🎬', 'words', 'romantic'),
('Acts of service...', 'Do my laundry', '🧺', 'I got myself', '💪', 'service', 'romantic'),
('Saying I love you...', 'Every 5 minutes', '⏰', 'When it matters', '✨', 'expression', 'romantic'),
('Compliment fishing...', 'Tell me I''m pretty', '🎣', 'Self-confident', '😎', 'validation', 'honest'),
('Random gifts...', 'Love surprises', '🎁', 'Just ask me first', '❓', 'spontaneity', 'romantic'),
('Planning dates...', 'Surprise me always', '🎉', 'I need to know', '📋', 'planning', 'lifestyle'),
('Remembering dates...', 'Photographic memory', '🧠', 'Calendar reminders', '📅', 'memory', 'honest'),

-- LIVING TOGETHER CHAOS
('Thermostat wars...', 'Arctic blast', '❄️', 'Sauna mode', '🔥', 'temperature', 'lifestyle'),
('Dishes policy...', 'Wash immediately', '🧽', 'Soak overnight', '🌙', 'cleaning', 'lifestyle'),
('Closet space...', '50/50 split', '⚖️', 'I need more', '👗', 'space', 'lifestyle'),
('Bed making...', 'Hospital corners', '🏥', 'What''s the point', '🤷', 'tidiness', 'lifestyle'),
('Grocery shopping...', 'List and coupons', '📝', 'Vibes only', '✨', 'organization', 'lifestyle'),
('Cooking duty...', 'Designated chef', '👨‍🍳', 'Rotate weekly', '🔄', 'chores', 'lifestyle'),
('TV remote control...', 'Fight for it', '⚔️', 'Share peacefully', '☮️', 'control', 'silly'),
('Sleeping positions...', 'Separate blankets', '🛏️', 'Tangled forever', '🥨', 'sleep', 'lifestyle'),
('Morning routine clash...', 'I need silence', '🤫', 'Chat immediately', '🗣️', 'morning', 'lifestyle'),
('Decorating style...', 'My aesthetic wins', '🎨', 'Compromise always', '🤝', 'home', 'lifestyle'),

-- SPICY HYPOTHETICALS
('Hall pass allowed...', 'Never ever', '🚫', 'We could discuss', '💬', 'boundaries', 'spicy'),
('Role play energy...', 'Oscar worthy', '🏆', 'Too awkward', '😅', 'creativity', 'spicy'),
('Toys and accessories...', 'Full collection', '🧰', 'Keep it simple', '✨', 'openness', 'spicy'),
('Taking photos...', 'If we''re both ok', '📸', 'Hard no', '🙅', 'boundaries', 'spicy'),
('Talking about past...', 'Full honesty', '📖', 'Don''t ask don''t tell', '🤐', 'history', 'honest'),
('Fantasy sharing...', 'Open book', '📚', 'Keep some mystery', '🎭', 'communication', 'spicy'),
('Bucket list stuff...', 'Try everything once', '☑️', 'Vanilla is valid', '🍦', 'adventure', 'spicy'),
('Surprise outfit...', 'Love the effort', '👔', 'Warn me first', '⚠️', 'spontaneity', 'spicy'),
('Flirting with others...', 'Harmless fun', '😇', 'Eyes on me only', '👁️', 'jealousy', 'honest'),
('Strip games...', 'Poker face ready', '🃏', 'Too competitive', '🏆', 'games', 'spicy'),

-- GEN-Z RELATIONSHIP TAKES
('Soft launching...', 'Post the hand', '✋', 'Wait for hard launch', '🚀', 'social', 'lifestyle'),
('Instagram official...', 'Grid post required', '📱', 'Stories enough', '⏰', 'social', 'lifestyle'),
('Relationship TikToks...', 'We''re content creators', '🎬', 'Keep us private', '🔒', 'social', 'lifestyle'),
('Couple aesthetic...', 'Matching everything', '👯', 'Individual style', '🎨', 'style', 'silly'),
('Talking stage length...', '2 weeks max', '⏱️', 'Take our time', '🐢', 'pace', 'flirty'),
('Situationship vibes...', 'Define it now', '📋', 'Go with the flow', '🌊', 'labels', 'honest'),
('Love bombing check...', 'Enjoy it', '💕', 'Red flag alert', '🚩', 'awareness', 'honest'),
('Breadcrumbing response...', 'Block immediately', '🚫', 'Give benefit of doubt', '🤔', 'standards', 'honest'),
('Benching acceptable...', 'Absolutely not', '❌', 'Sometimes happens', '🤷', 'standards', 'honest'),
('Orbiting your ex...', 'Normal behavior', '🌍', 'Move on please', '👋', 'boundaries', 'honest'),

-- CHAOTIC DATE IDEAS
('First date spot...', 'Fancy dinner', '🍽️', 'Casual coffee', '☕', 'style', 'flirty'),
('Adventure date...', 'Skydiving energy', '🪂', 'Picnic vibes', '🧺', 'adventure', 'flirty'),
('Movie date rules...', 'Sharing popcorn', '🍿', 'Own buckets', '🪣', 'sharing', 'silly'),
('Double date energy...', 'The more the merrier', '🎉', 'Just us please', '👫', 'social', 'lifestyle'),
('Staying in date...', 'Cook together', '👨‍🍳', 'Order delivery', '🛵', 'effort', 'lifestyle'),
('Spontaneous trip...', 'Pack in 10 min', '🧳', 'Need to plan', '📋', 'spontaneity', 'lifestyle'),
('Concert date...', 'Mosh pit energy', '🤘', 'Seats please', '💺', 'energy', 'lifestyle'),
('Beach or mountains...', 'Sand and waves', '🏖️', 'Hiking trails', '⛰️', 'nature', 'lifestyle'),
('Game night date...', 'Ultra competitive', '🏆', 'Let them win', '🎁', 'competition', 'silly'),
('Escape room vibes...', 'I''ll solve it all', '🧩', 'Teamwork makes dream', '🤝', 'teamwork', 'silly'),

-- ARGUMENT STYLES
('Fighting fair...', 'Never raise voice', '🤫', 'Express emotions', '😤', 'conflict', 'honest'),
('Silent treatment...', 'Never acceptable', '🚫', 'Sometimes needed', '🧘', 'conflict', 'honest'),
('Apologizing first...', 'Ego who', '🙇', 'Wait for them', '⏳', 'pride', 'honest'),
('Makeup energy after...', 'Immediately needed', '💋', 'Need space first', '🚀', 'reconciliation', 'spicy'),
('Bringing up old stuff...', 'Fair game', '🎯', 'Stay on topic', '📍', 'arguing', 'honest'),
('Involving friends...', 'Need outside input', '👥', 'Keep it between us', '🤐', 'privacy', 'honest'),
('Going to bed angry...', 'Never ever', '🚫', 'Sleep on it', '😴', 'conflict', 'honest'),
('Texting during fights...', 'Better than calling', '📱', 'Talk in person', '🗣️', 'communication', 'honest'),
('Saying sorry...', 'Words are enough', '💬', 'Actions required', '🎬', 'apology', 'honest'),
('Forgiving quickly...', 'Water under bridge', '🌊', 'Need time to process', '⏰', 'forgiveness', 'honest'),

-- TRUST AND LOYALTY
('Phone checking...', 'Nothing to hide', '📱', 'Privacy matters', '🔐', 'trust', 'honest'),
('Having close friends of opposite gender...', 'Totally fine', '✅', 'Sets boundaries', '🚧', 'trust', 'honest'),
('Telling white lies...', 'Sometimes necessary', '🤥', 'Always truth', '📖', 'honesty', 'honest'),
('Keeping secrets...', 'Some things private', '🤐', 'Full transparency', '🪟', 'honesty', 'honest'),
('Ex as friend...', 'Mature behavior', '🎓', 'Not comfortable', '😬', 'boundaries', 'honest'),
('Snooping temptation...', 'Would never', '😇', 'Maybe once checked', '👀', 'trust', 'honest'),
('Lying about location...', 'Deal breaker', '💔', 'Depends on context', '🤔', 'honesty', 'honest'),
('Financial secrets...', 'Share everything', '💰', 'Some independence ok', '🏦', 'money', 'honest'),
('Past relationship talk...', 'Full history', '📚', 'On a need to know', '🤷', 'history', 'honest'),
('Defending partner publicly...', 'Always ride or die', '🏍️', 'Depends on situation', '⚖️', 'loyalty', 'honest'),

-- FUTURE PLANNING
('Marriage timeline...', 'ASAP', '💍', 'No rush', '🐢', 'commitment', 'romantic'),
('Kids discussion...', 'Want them', '👶', 'Child-free life', '✈️', 'future', 'honest'),
('Pet parent first...', 'Fur babies yes', '🐕', 'Human babies only', '👶', 'pets', 'lifestyle'),
('Career vs relationship...', 'Balance is key', '⚖️', 'Love comes first', '💕', 'priorities', 'honest'),
('Long distance capable...', 'We''d make it work', '💪', 'Need physical presence', '🤗', 'distance', 'honest'),
('Moving for partner...', 'Anywhere with you', '🗺️', 'My city my rules', '🏙️', 'sacrifice', 'honest'),
('Financial goals...', 'Save everything', '🏦', 'YOLO spending', '💸', 'money', 'lifestyle'),
('Retirement dreams...', 'Beach house', '🏖️', 'City apartment', '🏙️', 'future', 'lifestyle'),
('Combining finances...', 'Joint account', '💳', 'Separate always', '📊', 'money', 'honest'),
('Supporting dreams...', 'Quit job for passion', '🎨', 'Stable income first', '💼', 'support', 'honest'),

-- RANDOM SPICY SCENARIOS
('Caught checking someone out...', 'Eyes have a mind', '👀', 'Only have eyes for you', '😍', 'loyalty', 'honest'),
('Celebrity crush allowed...', 'Fantasy is fine', '🌟', 'Still feels weird', '😬', 'jealousy', 'silly'),
('Flirty coworker...', 'Shut it down hard', '🛑', 'Harmless work chat', '💼', 'boundaries', 'honest'),
('DM from attractive stranger...', 'Ignore completely', '🙈', 'Polite decline', '👋', 'loyalty', 'honest'),
('Partner gains weight...', 'Love them same', '💕', 'Encourage health', '🏃', 'acceptance', 'honest'),
('Bad haircut reaction...', 'Lie and say cute', '🤥', 'Gentle honesty', '💬', 'honesty', 'silly'),
('Embarrassing them publicly...', 'All for the laughs', '😂', 'Never ever', '🙅', 'respect', 'silly'),
('Remembering first date...', 'Every detail', '🧠', 'General vibes only', '✨', 'memory', 'romantic'),
('Going through phases...', 'Support every era', '🎭', 'Consistency please', '📏', 'change', 'honest'),
('Different music tastes...', 'Convert them', '🎵', 'Headphones exist', '🎧', 'differences', 'lifestyle'),

-- MORE SPICY INTIMACY VIBES
('Eye contact during...', 'Soul connecting', '👁️', 'Too intense', '😳', 'intimacy', 'spicy'),
('Laughing during...', 'Best energy', '😂', 'Kills the mood', '💀', 'humor', 'spicy'),
('Noise level...', 'Neighbors know', '📢', 'Library quiet', '🤫', 'expression', 'spicy'),
('Quickie vs marathon...', 'Efficiency king', '⚡', 'Take your time', '🐢', 'pace', 'spicy'),
('Dirty talk...', 'Narrator mode', '🎙️', 'Actions only', '🎬', 'communication', 'spicy'),
('Location variety...', 'Every room', '🏠', 'Bedroom only', '🛏️', 'adventure', 'spicy'),
('Mirror placement...', 'Strategic viewing', '🪞', 'Too much', '🙈', 'visual', 'spicy'),
('Temperature preference...', 'AC blasting', '❄️', 'Heat it up', '🔥', 'comfort', 'spicy'),
('Outfit requests...', 'Happy to dress up', '👔', 'Come as you are', '🎸', 'effort', 'spicy'),
('Schedule preference...', 'Weekday energy', '📅', 'Weekend warriors', '🎉', 'timing', 'spicy'),

-- CHAOTIC COUPLE BEHAVIORS
('Sharing food...', 'What''s mine is yours', '🍴', 'Order your own', '🍽️', 'sharing', 'silly'),
('Stealing hoodies...', 'Collection growing', '🧥', 'Buy your own', '🛒', 'sharing', 'silly'),
('Bathroom sharing...', 'No boundaries', '🚿', 'Some privacy please', '🚪', 'comfort', 'silly'),
('Skincare routine together...', 'Couple masks', '🧖', 'My sacred time', '✨', 'bonding', 'lifestyle'),
('Gym together...', 'Motivation duo', '💪', 'Solo workout', '🏃', 'fitness', 'lifestyle'),
('Napping together...', 'Cuddle puddle', '😴', 'Separate naps', '🛋️', 'rest', 'lifestyle'),
('Showering together...', 'Saves water', '💧', 'Alone time needed', '🧘', 'privacy', 'spicy'),
('Karaoke duets...', 'Our song ready', '🎤', 'Solo acts only', '🎭', 'fun', 'silly'),
('Dance in kitchen...', 'Every meal prep', '💃', 'Too cheesy', '🧀', 'romance', 'romantic'),
('Baby talk to each other...', 'It''s our thing', '🍼', 'Absolutely not', '🚫', 'communication', 'silly'),

-- SOCIAL MEDIA ERA LOVE
('Posting anniversary...', 'Long caption essay', '📝', 'Private celebration', '🎂', 'social', 'lifestyle'),
('Checking their likes...', 'Casual scroll', '📱', 'Trust fully', '💯', 'trust', 'honest'),
('Ex still following...', 'Doesn''t matter', '🤷', 'Unfollow please', '❌', 'boundaries', 'honest'),
('Relationship status...', 'Facebook official', '📘', 'Who uses Facebook', '👴', 'social', 'lifestyle'),
('Couple content creation...', 'Brand deals coming', '💰', 'Keep love offline', '📴', 'social', 'lifestyle'),
('Vlogging dates...', 'Content is content', '📹', 'Live in moment', '✨', 'presence', 'lifestyle'),
('Rating on dating apps...', 'Uninstall together', '🗑️', 'Never installed', '😇', 'commitment', 'honest'),
('Sharing passwords...', 'Same password energy', '🔑', 'Individual security', '🔒', 'trust', 'honest'),
('Screen time together...', 'Parallel scrolling', '📱', 'Phone free zone', '📵', 'attention', 'lifestyle'),
('Spotify blend...', 'Musical soulmates', '🎵', 'Different vibes ok', '🎧', 'compatibility', 'lifestyle'),

-- OVER THE TOP ROMANCE
('Public proposals...', 'Flash mob ready', '💃', 'Intimate moment', '🕯️', 'style', 'romantic'),
('Love letters...', 'Handwritten always', '✍️', 'Texts are modern', '📱', 'expression', 'romantic'),
('Surprise parties...', 'Love them', '🎉', 'Hate surprises', '😰', 'surprises', 'lifestyle'),
('Serenading...', 'Guitar out', '🎸', 'Please don''t', '🙈', 'romance', 'romantic'),
('Sky writing...', 'Ultimate flex', '✈️', 'Environmental no', '🌍', 'gestures', 'over_the_top'),
('Billboard love...', 'Go big or home', '📺', 'Way too much', '😳', 'gestures', 'over_the_top'),
('Tattoo of name...', 'Commitment goals', '💉', 'Jinx it', '🤞', 'permanent', 'over_the_top'),
('Matching tattoos...', 'Forever symbol', '♾️', 'Separate designs', '🎨', 'commitment', 'over_the_top'),
('Star naming...', 'Cosmic love', '⭐', 'It''s a scam', '🤔', 'romance', 'over_the_top'),
('Writing a song...', 'Chart topper incoming', '🎵', 'Stick to playlist', '📋', 'creativity', 'romantic'),

-- REALISTIC RELATIONSHIP MOMENTS
('Sick day care...', 'Full nurse mode', '🏥', 'Give me space', '🚀', 'care', 'romantic'),
('Period support...', 'Heating pad ready', '🔥', 'Just ask what you need', '❓', 'support', 'romantic'),
('Bad day comfort...', 'Let me fix it', '🔧', 'Just listen', '👂', 'support', 'honest'),
('Stress response...', 'Talk it out', '🗣️', 'Need alone time', '🧘', 'coping', 'honest'),
('Crying together...', 'Emotional bonding', '😭', 'One at a time', '⏳', 'emotions', 'honest'),
('Embarrassing stories...', 'Share everything', '📖', 'Some secrets ok', '🤐', 'vulnerability', 'honest'),
('Meeting at worst...', 'Seen it all', '👀', 'Some mystery good', '✨', 'authenticity', 'honest'),
('Hangry moments...', 'Feed them quick', '🍔', 'Don''t take it personal', '🙏', 'understanding', 'silly'),
('Snoring solution...', 'Earplugs and love', '👂', 'Separate rooms option', '🚪', 'sleep', 'lifestyle'),
('Morning breath kiss...', 'Love conquers all', '💋', 'Brush first please', '🪥', 'comfort', 'silly'),

-- HOLIDAY AND FAMILY
('Holiday spending...', 'Go all out', '🎁', 'Budget conscious', '💰', 'money', 'lifestyle'),
('Family time balance...', 'My family more', '👨‍👩‍👧', 'Equal split', '⚖️', 'family', 'lifestyle'),
('In-law relationship...', 'Best friends', '🤝', 'Polite distance', '📏', 'family', 'lifestyle'),
('Holiday traditions...', 'Create new ones', '✨', 'Keep the classics', '🎄', 'traditions', 'lifestyle'),
('Birthday expectations...', 'Surprise party', '🎉', 'Low key celebration', '🎂', 'celebrations', 'lifestyle'),
('Valentine''s Day...', 'Grand romantic gestures', '💝', 'Capitalism holiday', '💸', 'romance', 'romantic'),
('New Year''s kiss...', 'Midnight countdown', '🕛', 'Probably asleep', '😴', 'traditions', 'romantic'),
('Couple costumes...', 'Iconic duo', '👫', 'Individual costumes', '🎭', 'fun', 'silly'),
('Family photos...', 'Matching outfits', '👔', 'Coordinated colors', '🎨', 'aesthetics', 'lifestyle'),
('Holiday cards...', 'Professional photoshoot', '📸', 'Casual selfie', '🤳', 'effort', 'lifestyle'),

-- DEEP RELATIONSHIP QUESTIONS
('Soulmates real...', 'One true love', '💕', 'Many compatible people', '🌍', 'beliefs', 'romantic'),
('Love at first sight...', 'Absolutely', '😍', 'Lust at first sight', '🔥', 'beliefs', 'romantic'),
('Completing each other...', 'Two halves whole', '🧩', 'Two whole people', '💪', 'independence', 'honest'),
('Changing for partner...', 'Growth together', '🌱', 'Accept as is', '✅', 'change', 'honest'),
('Relationship work...', 'Constant effort', '💪', 'Flows naturally', '🌊', 'effort', 'honest'),
('Passion vs stability...', 'Fireworks always', '🎆', 'Comfortable love', '🛋️', 'preference', 'honest'),
('Best friend or lover...', 'Why not both', '🤝', 'Different roles', '🎭', 'connection', 'romantic'),
('Growing apart fear...', 'Work to prevent', '🔧', 'Natural sometimes', '🍂', 'reality', 'honest'),
('One that got away...', 'Everyone has one', '💔', 'No regrets', '✨', 'past', 'honest'),
('Dying together old...', 'Relationship goals', '👴', 'Morbid thought', '💀', 'future', 'romantic'),

-- MORE FUN CHAOS
('Conspiracy theories together...', 'Late night rabbit holes', '🐰', 'Stay grounded', '🌍', 'fun', 'silly'),
('True crime podcasts...', 'Solve it together', '🔍', 'Too dark', '😰', 'hobbies', 'lifestyle'),
('Reality TV watching...', 'Trash TV bonding', '📺', 'Brain rot no thanks', '🧠', 'entertainment', 'lifestyle'),
('Gaming together...', 'Co-op only', '🎮', 'Competitive rivals', '⚔️', 'gaming', 'lifestyle'),
('Reading same book...', 'Book club vibes', '📚', 'Different genres', '📖', 'hobbies', 'lifestyle'),
('Learning together...', 'Take a class', '📝', 'Teach each other', '👨‍🏫', 'growth', 'lifestyle'),
('Workout competition...', 'Fitness rivalry', '🏆', 'Encourage not compete', '🤗', 'fitness', 'lifestyle'),
('Cooking competition...', 'MasterChef home', '👨‍🍳', 'Team cooking', '🍳', 'fun', 'lifestyle'),
('Road trip roles...', 'DJ and navigator', '🗺️', 'Take turns driving', '🚗', 'travel', 'lifestyle'),
('IKEA test...', 'Passed with flying colors', '✅', 'Nearly broke up', '😅', 'teamwork', 'silly'),

-- VULNERABILITY AND GROWTH
('Admitting wrong...', 'Easy to say sorry', '🙏', 'Struggle with ego', '😤', 'humility', 'honest'),
('Showing weakness...', 'Full vulnerability', '😢', 'Stay strong facade', '💪', 'openness', 'honest'),
('Asking for help...', 'Team effort', '🤝', 'Independence first', '🦸', 'dependence', 'honest'),
('Therapy together...', 'Couples counseling yes', '🛋️', 'Work it out ourselves', '💪', 'help', 'honest'),
('Personal therapy...', 'Self work important', '🧘', 'Not for me', '🤷', 'growth', 'honest'),
('Reading self help...', 'Always improving', '📚', 'Naturally good', '😎', 'growth', 'honest'),
('Meditation together...', 'Spiritual connection', '🧘', 'Solo practice', '🙏', 'spirituality', 'lifestyle'),
('Journaling about relationship...', 'Process through writing', '✍️', 'Live in moment', '✨', 'reflection', 'lifestyle'),
('Setting goals together...', 'Vision board couple', '📋', 'Go with flow', '🌊', 'planning', 'lifestyle'),
('Celebrating small wins...', 'Every victory counts', '🎉', 'Save it for big ones', '🏆', 'celebration', 'lifestyle'),

-- MONEY MATTERS
('Splitting bills...', '50/50 always', '⚖️', 'Proportional to income', '📊', 'money', 'honest'),
('Expensive gifts...', 'Go big or go home', '💎', 'Thoughtful over pricey', '💭', 'gifts', 'romantic'),
('Saving vs spending...', 'Save for future', '🏦', 'Enjoy the present', '🎉', 'money', 'lifestyle'),
('Financial advisor...', 'Professional help', '📈', 'Figure it out ourselves', '🤓', 'money', 'lifestyle'),
('Prenup thoughts...', 'Smart planning', '📋', 'Jinxes marriage', '🤞', 'money', 'honest'),
('Debt disclosure...', 'Full transparency', '📊', 'Personal business', '🤐', 'honesty', 'honest'),
('Impulse purchases...', 'Treat yourself', '🛍️', 'Budget first', '💰', 'spending', 'lifestyle'),
('Joint credit card...', 'Shared responsibility', '💳', 'Separate finances', '📊', 'money', 'lifestyle'),
('Investing together...', 'Build wealth together', '📈', 'Separate portfolios', '💼', 'money', 'lifestyle'),
('Lending to family...', 'Always help family', '👨‍👩‍👧', 'Our money first', '💰', 'money', 'honest'),

-- FRIENDSHIP IN RELATIONSHIP
('Best friend status...', 'They''re my bestie', '🤝', 'Partner different than friend', '💕', 'connection', 'romantic'),
('Separate friend groups...', 'Healthy independence', '👥', 'Share everything', '🤗', 'social', 'lifestyle'),
('Friends'' opinions matter...', 'Value their input', '💬', 'Our relationship our business', '🔒', 'boundaries', 'honest'),
('Double dating frequency...', 'Weekly hangs', '📅', 'Occasional only', '🗓️', 'social', 'lifestyle'),
('Vacation with friends...', 'The more the merrier', '🎉', 'Couple trips only', '👫', 'travel', 'lifestyle'),
('Friend drama involvement...', 'Full support mode', '🤝', 'Stay neutral', '⚖️', 'loyalty', 'honest'),
('Partner''s friends...', 'Love them all', '💕', 'Tolerate them', '😬', 'social', 'honest'),
('Your friends opinion of partner...', 'Need approval', '✅', 'My choice matters most', '🙋', 'independence', 'honest'),
('Making friends as couple...', 'Couple friends hunting', '🎯', 'Individual friendships', '👤', 'social', 'lifestyle'),
('Friend breakup support...', 'There for them completely', '🤗', 'Let them process alone', '🧘', 'support', 'honest'),

-- COMMUNICATION STYLES
('Texting frequency...', 'Constant updates', '📱', 'Check in few times', '⏰', 'communication', 'lifestyle'),
('Phone calls vs text...', 'Hear your voice', '📞', 'Text is easier', '💬', 'communication', 'lifestyle'),
('Deep talks timing...', 'Late night hours', '🌙', 'Daytime discussions', '☀️', 'communication', 'lifestyle'),
('Sharing feelings...', 'Open book always', '📖', 'Process first then share', '🤔', 'emotions', 'honest'),
('Handling criticism...', 'Welcome feedback', '✅', 'Sensitive about it', '😢', 'growth', 'honest'),
('Expressing anger...', 'Let it out', '😤', 'Cool down first', '❄️', 'emotions', 'honest'),
('Silent treatment...', 'Never use it', '🚫', 'Sometimes need space', '🧘', 'conflict', 'honest'),
('Interrupting habits...', 'Excited to share', '🗣️', 'Always let them finish', '🤐', 'listening', 'honest'),
('Remembering conversations...', 'Photographic memory', '🧠', 'Repeat things often', '🔄', 'attention', 'honest'),
('Non-verbal communication...', 'Read them perfectly', '👀', 'Need words', '💬', 'understanding', 'honest'),

-- QUIRKS AND HABITS
('Snoring accepted...', 'White noise', '😴', 'Separate rooms maybe', '🚪', 'sleep', 'lifestyle'),
('Weird food combos...', 'Try everything', '🍴', 'Keep it normal', '😅', 'acceptance', 'silly'),
('Singing in shower...', 'Concert daily', '🎤', 'Peaceful silence', '🤫', 'quirks', 'silly'),
('Dancing randomly...', 'Any time any place', '💃', 'Need music at least', '🎵', 'spontaneity', 'silly'),
('Talking to pets...', 'Full conversations', '🐕', 'Normal pet owner', '😊', 'quirks', 'silly'),
('Sleep talking...', 'Entertaining content', '💬', 'Kind of creepy', '😰', 'sleep', 'silly'),
('Blanket hogging...', 'Survival of fittest', '🥶', 'Sharing is caring', '🤗', 'sleep', 'silly'),
('Thermostat touching...', 'Constant adjusting', '🌡️', 'Set it and forget', '😌', 'comfort', 'lifestyle'),
('Leaving lights on...', 'Safety thing', '💡', 'Waste of electricity', '⚡', 'habits', 'lifestyle'),
('Toilet seat debate...', 'Leave it up', '🚽', 'Always down', '👇', 'consideration', 'silly'),

-- HANDLING DIFFERENCES
('Political differences...', 'Can work through it', '🤝', 'Deal breaker', '🚫', 'values', 'honest'),
('Religious differences...', 'Respect each other', '🙏', 'Same beliefs needed', '⛪', 'values', 'honest'),
('Diet differences...', 'Cook separate meals', '🍽️', 'Eat same thing', '🤝', 'lifestyle', 'lifestyle'),
('Cleanliness standards...', 'I''m the messy one', '🧹', 'I''m the clean one', '✨', 'habits', 'lifestyle'),
('Introvert extrovert mix...', 'Balance each other', '⚖️', 'Same energy needed', '🔋', 'personality', 'honest'),
('Morning person vs night owl...', 'Opposite attract', '🧲', 'Same schedule better', '⏰', 'lifestyle', 'lifestyle'),
('Spending habits clash...', 'Work it out', '💰', 'Major issue', '🚨', 'money', 'honest'),
('Family closeness levels...', 'Adapt to each other', '👨‍👩‍👧', 'Causes tension', '😬', 'family', 'honest'),
('Career ambition levels...', 'Support any level', '💪', 'Need similar drive', '🚀', 'career', 'honest'),
('Adventure comfort levels...', 'Push each other', '🏔️', 'Respect boundaries', '🚧', 'adventure', 'lifestyle'),

-- RANDOM COUPLE SCENARIOS
('Farting in front of each other...', 'True intimacy', '💨', 'Some mystery please', '🎭', 'comfort', 'silly'),
('Popping each other''s pimples...', 'Gross but intimate', '😬', 'Hard boundary', '🚫', 'comfort', 'silly'),
('Sharing toothbrush...', 'Emergency ok', '🪥', 'Never ever', '🤢', 'boundaries', 'silly'),
('Finish their food...', 'Always ask first', '🍽️', 'Fair game', '🎯', 'sharing', 'silly'),
('Read their texts...', 'Open phone policy', '📱', 'Privacy respected', '🔒', 'trust', 'honest'),
('Know their passwords...', 'Share everything', '🔑', 'Not necessary', '🤷', 'trust', 'honest'),
('Track their location...', 'Safety reasons', '📍', 'Trust instead', '💕', 'trust', 'honest'),
('Going through camera roll...', 'Nothing to hide', '📸', 'Ask permission first', '🙋', 'privacy', 'honest'),
('Reading diary or journal...', 'Absolute no', '🚫', 'If they share ok', '📖', 'boundaries', 'honest'),
('Keeping ex''s gifts...', 'Memories are ok', '📦', 'Throw it all out', '🗑️', 'past', 'honest'),

-- MORE INTIMACY QUESTIONS
('Initiating frequency...', 'Multiple times daily', '🔥', 'Weekly is fine', '📅', 'drive', 'spicy'),
('Rejection handling...', 'Totally understand', '🤗', 'Feel hurt honestly', '😢', 'emotions', 'spicy'),
('Scheduling intimacy...', 'Keeps it alive', '📅', 'Kills spontaneity', '❌', 'approach', 'spicy'),
('After kids intimacy...', 'Make time priority', '⏰', 'Natural decrease ok', '🤷', 'future', 'spicy'),
('Long term passion...', 'Keep the spark', '✨', 'Comfort over passion', '🛋️', 'longevity', 'spicy'),
('Trying partner''s fantasy...', 'Open to most things', '🎭', 'Within my comfort', '🛡️', 'openness', 'spicy'),
('Watching adult content together...', 'Could be fun', '📺', 'Not for us', '🚫', 'boundaries', 'spicy'),
('Reading spicy books together...', 'Book club energy', '📚', 'Solo reading', '🙈', 'activities', 'spicy'),
('Couple''s massages...', 'Professional setting', '💆', 'Just us at home', '🏠', 'activities', 'romantic'),
('Spa day together...', 'Pamper each other', '🧖', 'Solo self care', '🧘', 'bonding', 'romantic'),

-- COMMITMENT TESTS
('Would you wait for them...', 'Forever if needed', '⏳', 'Reasonable time limit', '⏰', 'commitment', 'romantic'),
('Long distance survival...', 'Love conquers distance', '✈️', 'Need physical presence', '🤗', 'distance', 'honest'),
('Supporting through illness...', 'In sickness and health', '🏥', 'Depends on severity', '🤔', 'commitment', 'honest'),
('Financial hardship together...', 'Weather any storm', '🌧️', 'Causes serious stress', '😰', 'resilience', 'honest'),
('Career change support...', 'Follow your dreams', '🌟', 'Consider practicality', '📊', 'support', 'honest'),
('Going back to school...', 'Education investment', '🎓', 'Financial burden', '💰', 'support', 'honest'),
('Starting a business together...', 'Power couple goals', '💪', 'Keep work separate', '🏢', 'partnership', 'lifestyle'),
('Moving countries for partner...', 'Adventure awaits', '🌍', 'Too big a sacrifice', '😬', 'commitment', 'honest'),
('Giving up hobby for relationship...', 'Never should have to', '🚫', 'Compromise sometimes', '⚖️', 'sacrifice', 'honest'),
('Defending partner to family...', 'Always their side', '🛡️', 'Family matters too', '👨‍👩‍👧', 'loyalty', 'honest'),

-- FINAL RAPID FIRE
('Love language primary...', 'Physical touch', '🤗', 'Words of affirmation', '💬', 'love_language', 'romantic'),
('Ideal date night...', 'Fancy restaurant', '🍽️', 'Home cooked meal', '🏠', 'date', 'romantic'),
('Morning greeting...', 'Kiss first thing', '💋', 'Coffee first please', '☕', 'morning', 'romantic'),
('Goodnight ritual...', 'Always say it', '🌙', 'Fall asleep randomly', '😴', 'night', 'romantic'),
('PDA comfort level...', 'Full display', '💏', 'Hand holding max', '🤝', 'public', 'romantic'),
('Jealousy level...', 'Hardly ever', '😇', 'Green monster sometimes', '💚', 'jealousy', 'honest'),
('Trust level...', 'Complete 100%', '💯', 'Building slowly', '🧱', 'trust', 'honest'),
('Communication rating...', 'Talk about everything', '🗣️', 'Could improve', '📈', 'communication', 'honest'),
('Laughter frequency...', 'Constantly together', '😂', 'Comfortable silence ok', '🤫', 'humor', 'romantic'),
('Future excitement...', 'Can''t wait', '🚀', 'Taking it day by day', '📅', 'future', 'romantic');
